### ISSUE TITLE
<head> tag문제

### ISSUE THREAD

**Issue by backjaehyun** [backjaehyun/python-ogp#1]
http://outstanding.kr/sns%EB%A5%BC-%EA%B2%BD%EC%9F%81%EB%A0%A5%EC%9C%BC%EB%A1%9C-%EC%82%BC%EB%8A%94-%EC%98%A4%ED%94%BC%EB%8B%88%EC%96%B8-%EB%A6%AC%EB%8D%94-10%E4%BA%BA/

개발자도구로 보면 head tag가 있는데
bs로 열어보면 head tag가 없고 meta가 쭉 나열되어있음
bs.html.head가 None이 나와버림

**Comment by backjaehyun** [comment]
head를 실수로 빼먹었는데 브라우저가 고쳐준다거나...

**Comment by younseunghyun** [comment]
음... 아마도 사이트안에서 자바스크립트로 헤더 태그 로딩하는 부분이 있어서 그런거 같은데...

**Comment by backjaehyun** [comment]
http://instantclick.io/click-test
이 유알엘도 head가 없지만 meta들은 있어요 !
soup.meta
soup.find_all('meta')
해도 그냥 전체 숩이 나와버려요

혹시나 html/head/body tag등이 optional이지 않을까 해서 본 자료에요!
:http://www.w3.org/TR/2011/WD-html5-20110525/syntax.html#optional-tags

**Comment by backjaehyun** [comment]
자바스크립트 로딩부분도 고려해서 찾아볼게요!!
